controller:
  replicaCount: 1

  nodeSelector:
    workload: platform

  tolerations:
    - key: 'workload'
      operator: 'Equal'
      value: 'platform'
      effect: 'NoSchedule'

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
    externalTrafficPolicy: Local

  metrics:
    enabled: true

  ingressClassResource:
    enabled: true
    name: nginx
    controllerValue: k8s.io/ingress-nginx

  watchIngressWithoutClass: true

  admissionWebhooks:
    patch:
      nodeSelector:
        workload: platform
      tolerations:
        - key: 'workload'
          operator: 'Equal'
          value: 'platform'
          effect: 'NoSchedule'
