apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-api
  namespace: catalog-api
  labels:
    azure.workload.identity/use: 'true'
  annotations:
    azure.workload.identity/client-id: 'bf3a1769-3d8d-41dc-a79f-aa748852f58f'
