apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: catalog-api
  labels:
    app: catalog-api
spec:
  selector:
    app: catalog-api
  ports:
    - name: http
      port: 80
      targetPort: 4101
      protocol: TCP
