apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-api-ingress
  namespace: demo-api
spec:
  ingressClassName: nginx
  rules:
    - host: demo.continuecode.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-api-svc
                port:
                  number: 80
